TESTPROGS += parse/a-info \
	parse/blowe \
	parse/blowm \
	parse/brand \
	parse/curse \
	parse/c-info \
	parse/e-info \
	parse/f-info \
	parse/flavor \
	parse/graphics \
	parse/h-info \
	parse/k-info \
	parse/lore \
	parse/mbase \
	parse/names \
	parse/objact \
	parse/objbase \
	parse/objprop \
	parse/p-info \
	parse/pain \
	parse/parse \
	parse/pit \
	parse/proj \
	parse/ptimed \
	parse/r-info \
	parse/readstore \
	parse/slay \
	parse/v-info \
	parse/z-info
