MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = amb_bell_metal1.mp3		mco_scurry_dry.mp3		plm_drop_boot.mp3 \
	amb_bell_metal2.mp3		mco_shake_roll.mp3		plm_eat_bite.mp3 \
	amb_bell_tibet1.mp3		mco_snarl_short.mp3		plm_floor_creak.mp3 \
	amb_bell_tibet2.mp3		mco_spray_long.mp3		plm_floor_creak2.mp3 \
	amb_bell_tibet3.mp3		mco_squish_hit.mp3		plm_glass_break.mp3 \
	amb_door_doom.mp3		mco_squish_snap.mp3		plm_glass_breaking.mp3 \
	amb_door_iron.mp3		mco_strange_music.mp3		plm_glass_smashing.mp3 \
	amb_dungeon_echo.mp3		mco_strange_thwoink.mp3		plm_jar_ding.mp3 \
	amb_dungeon_echowet.mp3		mco_thoing_backwards.mp3	plm_levelup.mp3 \
	amb_gong_chinese.mp3		mco_thoing_deep.mp3		plm_lock_case.mp3 \
	amb_gong_low.mp3		mco_thud_crash.mp3		plm_lock_distant.mp3 \
	amb_gong_strike.mp3		mco_tube_hit.mp3		plm_metal_clank.mp3 \
	amb_gong_undertone.mp3		plc_bell_warn.mp3		plm_metal_sharpen.mp3 \
	amb_guitar_chord.mp3		plc_die_laugh.mp3		plm_open_case.mp3 \
	amb_pulse_low.mp3		plc_hit_anvil.mp3		plm_spell1.mp3 \
	amb_thunder_rain.mp3		plc_hit_anvil2.mp3		plm_spell2.mp3 \
	amb_thunder_roll.mp3		plc_hit_arrow.mp3		plm_spell3.mp3 \
	id_bad_aww.mp3			plc_hit_body.mp3		plm_use_staff.mp3 \
	id_bad_dang.mp3			plc_hit_groan.mp3		plm_wood_thud.mp3 \
	id_bad_hmm.mp3			plc_hit_grunt.mp3		plm_zap_rod.mp3 \
	id_bad_hmph.mp3			plc_hit_grunt2.mp3		pls_bell_bowl.mp3 \
	id_bad_ohh.mp3			plc_hit_hay.mp3			pls_bell_chime_new.mp3 \
	id_ego_whoa.mp3			plc_miss_arrow.mp3		pls_bell_glass.mp3 \
	id_ego_woohoo.mp3		plc_miss_arrow2.mp3		pls_bell_hibell_soft.mp3 \
	id_ego_yeah.mp3			plc_miss_swish.mp3		pls_bell_mute.mp3 \
	id_ego_yeah2.mp3		plm_aim_wand.mp3		pls_bell_sustain.mp3 \
	id_ego_yes.mp3			plm_bang_ceramic.mp3		pls_breathe_in.mp3 \
	id_good_hey.mp3			plm_bang_dumpster.mp3		pls_man_argoh.mp3 \
	id_good_hey2.mp3		plm_bang_metal.mp3		pls_man_gulp_new.mp3 \
	id_good_hmm.mp3			plm_book_pageturn.mp3		pls_man_oooh.mp3 \
	id_good_huh.mp3			plm_bottle_clinks.mp3		pls_man_scream2.mp3 \
	id_good_ooh.mp3			plm_break_canister.mp3		pls_man_sigh.mp3 \
	id_good_ooo.mp3			plm_break_glass.mp3		pls_man_sniff.mp3 \
	id_good_wow.mp3			plm_break_glass2.mp3		pls_man_sob.mp3 \
	mco_attack_breath.mp3		plm_break_plates.mp3		pls_man_spit.mp3 \
	mco_attack_spray.mp3		plm_break_shatter.mp3		pls_man_ugh.mp3 \
	mco_bite_chew.mp3		plm_break_smash.mp3		pls_man_yell.mp3 \
	mco_bite_chomp.mp3		plm_break_wood.mp3		pls_tone_blurk.mp3 \
	mco_bite_dainty.mp3		plm_cabinet_open.mp3		pls_tone_clave6.mp3 \
	mco_bite_gnash.mp3		plm_cabinet_shut.mp3		pls_tone_clavelo8.mp3 \
	mco_bite_hard.mp3		plm_chain_light.mp3		pls_tone_conk.mp3 \
	mco_bite_long.mp3		plm_chest_latch.mp3		pls_tone_elec.mp3 \
	mco_bite_munch.mp3		plm_chest_unlatch.mp3		pls_tone_goblet.mp3 \
	mco_bite_regular.mp3		plm_chimes_jangle.mp3		pls_tone_guiro.mp3 \
	mco_bite_short.mp3		plm_click_dry.mp3		pls_tone_headstock.mp3 \
	mco_bite_small.mp3		plm_click_switch.mp3			pls_tone_scrape.mp3 \
	mco_bite_soft.mp3		plm_click_switch2.mp3		pls_tone_stick.mp3 \
	mco_card_shuffle.mp3		plm_click_switch3.mp3		sto_bell_desk.mp3 \
	mco_castanet_trill.mp3		plm_click_wood.mp3		sto_bell_ding.mp3 \
	mco_ceramic_trill.mp3		plm_close_hatch.mp3		sto_bell_dingaling.mp3 \
	mco_click_vibra.mp3		plm_coins_dump.mp3		sto_bell_jingles.mp3 \
	mco_creature_choking.mp3	plm_coins_light.mp3		sto_bell_register1.mp3 \
	mco_creature_groan.mp3		plm_coins_pour.mp3		sto_bell_register2.mp3 \
	mco_creature_yelp.mp3		plm_coins_shake.mp3		sto_bell_ringing.mp3 \
	mco_cuica_rubbing.mp3		plm_cork_pop.mp3		sto_bell_shop.mp3 \
	mco_dino_low.mp3		plm_cork_squeak.mp3		sto_coins_countertop.mp3 \
	mco_dino_slur.mp3		plm_door_bolt.mp3		sto_man_haha.mp3 \
	mco_dino_talk.mp3		plm_door_creak.mp3		sto_man_hey.mp3 \
	mco_dino_yawn.mp3		plm_door_creakshut.mp3		sto_man_whoohaha.mp3 \
	mco_dub_wobble.mp3		plm_door_dungeon.mp3		sum_angel_song.mp3 \
	mco_frog_trill.mp3		plm_door_echolock.mp3		sum_bell_crystal.mp3 \
	mco_hit_whip.mp3		plm_door_entrance.mp3		sum_bell_hand.mp3 \
	mco_howl_croak.mp3		plm_door_knob.mp3		sum_bell_tone.mp3 \
	mco_howl_deep.mp3		plm_door_latch.mp3		sum_chime_jangle.mp3 \
	mco_howl_distressed.mp3		plm_door_open.mp3		sum_ghost_moan.mp3 \
	mco_howl_high.mp3		plm_door_opening.mp3		sum_ghost_oooo.mp3 \
	mco_howl_long.mp3		plm_door_rusty.mp3		sum_ghost_wail.mp3 \
	mco_liquid_squirt.mp3		plm_door_shut.mp3		sum_gong_temple.mp3 \
	mco_man_mumble.mp3		plm_door_slam.mp3		sum_laugh_evil2.mp3 \
	mco_mouse_squeaks.mp3		plm_door_squeaky.mp3		sum_lion_growl.mp3  \
	mco_rubber_thud.mp3		plm_door_wooden.mp3		sum_piano_scrape.mp3

PACKAGE = sounds

