#------------------------------------------------------------------------------
.SUFFIXES:
#------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

include $(DEVKITARM)/ds_rules

#------------------------------------------------------------------------------
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing extra header files
# DATA is a list of directories containing binary files
# all directories are relative to this makefile
#	IN THIS MODIFIED VERSION, YOU MAY ONLY HAVE ONE SOURCE DIRECTORY!!
#------------------------------------------------------------------------------
TARGET		:=	$(NAME)
BUILD		:=	$(CURDIR)
SOURCES		:=	$(CURDIR)/nds
#INCLUDES	:=	sys/nds/arm7/include
INCLUDES	:=
DATA		:=

#------------------------------------------------------------------------------
# any extra libraries we wish to link with the project
#------------------------------------------------------------------------------
LIBS	:= -lnds7
 
#------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level 
# containing include and lib
#------------------------------------------------------------------------------
LIBDIRS	:=	$(LIBNDS)
 
#------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add 
# additional rules for different file extensions
#------------------------------------------------------------------------------
 
export ARM7BIN	:=	$(BUILD)/$(TARGET).arm7
export ARM7ELF	:=	$(BUILD)/$(TARGET).arm7.elf
export DEPSDIR := $(BUILD)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir))
 
CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))
 
#------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
#------------------------------------------------------------------------------
	export LD	:=	$(CC)
#------------------------------------------------------------------------------
else
#------------------------------------------------------------------------------
	export LD	:=	$(CXX)
#------------------------------------------------------------------------------
endif
#------------------------------------------------------------------------------

export OFILES	:=	$(addsuffix .o,$(BINFILES)) \
				$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
 
export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
			$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
			-I$(CURDIR)/$(BUILD)
 
export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)
 
#------------------------------------------------------------------------------
# options for code generation
#------------------------------------------------------------------------------
ARCH	:=	-mthumb -mthumb-interwork

# note: arm9tdmi isn't the correct CPU arch, but anything newer and LD
# *insists* it has a FPU or VFP, and it won't take no for an answer!
CFLAGS	:=	-g -Wall -O2\
 			-mcpu=arm7tdmi -mtune=arm7tdmi -fomit-frame-pointer\
			-ffast-math \
			$(ARCH)

CFLAGS	+=	$(INCLUDE) -DARM7
CXXFLAGS	:=	$(CFLAGS) -fno-rtti -fno-exceptions

ASFLAGS	:=	-g $(ARCH)
LDFLAGS	=	-specs=ds_arm7.specs -g $(ARCH) -mno-fpu -Wl,-Map,$(BUILD)/$(TARGET).arm7.map

.PHONY: all clean
  
#------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD)/$(TARGET).arm7 $(BUILD)/$(TARGET).arm7.elf
 
 
#------------------------------------------------------------------------------
 
DEPENDS	:=	$(OFILES:.o=.d)
 
#------------------------------------------------------------------------------
# main targets
#------------------------------------------------------------------------------
all	:	$(ARM7BIN)

$(ARM7BIN)	:	$(ARM7ELF)
	@$(OBJCOPY) -O binary $< $@
	@echo built ... $(notdir $@)

$(ARM7ELF)	:	$(foreach ofile,$(OFILES),$(BUILD)/$(ofile))
	@echo linking $(notdir $@)
	@$(LD)  $(LDFLAGS) $(foreach ofile,$(OFILES),$(BUILD)/$(ofile)) \
		$(LIBPATHS) $(LIBS) -o $@
	
$(BUILD)/%.o	:	$(SOURCES)/%.c
	@echo $(notdir $<)
	$(CC) -MMD -MP -MF $(DEPSDIR)/$*.d $(CFLAGS) -c $< -o $@
	
#------------------------------------------------------------------------------
# you need a rule like this for each extension you use as binary data 
#------------------------------------------------------------------------------
%.bin.o	:	%.bin
#------------------------------------------------------------------------------
	@echo $(notdir $<)
	@$(bin2o)


-include $(DEPENDS)

#------------------------------------------------------------------------------