MKPATH=../../mk/
include $(MKPATH)buildsys.mk

# Don't need to do anything with the archive directory.  It's here for the
# with-no-install case; other installation modes will use a directory in
# the user's directory and don't need to install anything for it.
SUBDIRS = panic save scores
PACKAGE = user

