MACRO(CONFIGURE_GCU_FRONTEND _NAME_TARGET)

    # 3.10 required for CURSES_NEED_WIDE
    CMAKE_MINIMUM_REQUIRED(VERSION 3.10 FATAL_ERROR)
    SET(CURSES_NEED_WIDE TRUE)
    # Only ncurses provides wide character support so require that as well.
    SET(CURSES_NEED_NCURSES TRUE)
    FIND_PACKAGE(Curses)

    IF (CURSES_FOUND)

        TARGET_LINK_LIBRARIES(${_NAME_TARGET} PRIVATE ${CURSES_LIBRARIES})
        TARGET_INCLUDE_DIRECTORIES(${_NAME_TARGET} PRIVATE ${CURSES_INCLUDE_DIRS})
        TARGET_COMPILE_DEFINITIONS(${_NAME_TARGET} PRIVATE -D USE_GCU)
        TARGET_COMPILE_DEFINITIONS(${_NAME_TARGET} PRIVATE -D USE_NCURSES)

        MESSAGE(STATUS "Support for GCU front end - Ready")

    ELSE()

        MESSAGE(FATAL_ERROR "Support for GCU front end - Failed")

    ENDIF()

ENDMACRO()
