MACRO(CONFIGURE_SDL_SOUND _NAME_TARGET)

    FIND_PACKAGE(SDL_mixer)

    IF(SDL_MIXER_FOUND)

        TARGET_LINK_LIBRARIES(${_NAME_TARGET} PRIVATE ${SDL_MIXER_LIBRARIES})
        TARGET_INCLUDE_DIRECTORIES(${_NAME_TARGET} PRIVATE ${SDL_MIXER_INCLUDE_DIRS})
        TARGET_COMPILE_DEFINITIONS(${_NAME_TARGET} PRIVATE -D SOUND_SDL)
        TARGET_COMPILE_DEFINITIONS(${_NAME_TARGET} PRIVATE -D SOUND)

        MESSAGE(STATUS "Support for sound with SDL - Ready")

    ELSE()

        MESSAGE(FATAL_ERROR "Support for sound with SDL - Failed")

    ENDIF()

ENDMACRO()
