macro(configure_stats_backend _NAME_TARGET _ONLY_LINK)
    set(PREVIOUS_INVOCATION ${CONFIGURE_STATS_BACKEND_INVOKED_PREVIOUSLY})
    if(NOT ${_ONLY_LINK})
        target_compile_definitions(${_NAME_TARGET} PRIVATE -D USE_STATS)
    endif()
    find_library(MATH_LIBRARY m)
    if(MATH_LIBRARY)
        target_link_libraries(${_NAME_TARGET} PRIVATE ${MATH_LIBRARY})
    endif()
    if(NOT PREVIOUS_INVOCATION)
        message(STATUS "Support for statistics backend - Ready")
    endif()
    set(CONFIGURE_STATS_BACKEND_INVOKED_PREVIOUSLY YES CACHE
        INTERNAL "Mark if CONFIGURE_STATS_BACKEND called successfully" FORCE)
endmacro()
