MACRO(CONFIGURE_STATS_BACKEND _NAME_TARGET)

    TARGET_COMPILE_DEFINITIONS(${_NAME_TARGET} PRIVATE -D USE_STATS)
    FIND_LIBRARY(MATH_LIBRARY m)
    IF(MATH_LIBRARY)
        TARGET_LINK_LIBRARIES(${_NAME_TARGET} PRIVATE ${MATH_LIBRARY})
    ENDIF()
    MESSAGE(STATUS "Support for statistics backend - Ready")

ENDMACRO()
