MKPATH=../../../mk/
include $(MKPATH)rules.mk
include $(MKPATH)objective.mk

OBJECTIVE_DATA = \
	att-16.png:$(DATA_PATH)/xtra/icon \
	att-32.png:$(DATA_PATH)/xtra/icon \
	att-128.png:$(DATA_PATH)/xtra/icon \
	att-256.png:$(DATA_PATH)/xtra/icon \
	att-512.png:$(DATA_PATH)/xtra/icon \
