.\" Hey, Emacs! This is an -*- nroff -*- source file.
.\" Copyright (c) 1997 Manoj Srivastava <srivasta@debian.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.\" arch-tag: 393fc0e6-b0d3-42a9-a5d7-265743f99582
.\" $Id: angband.man,v 1.5 2002/01/17 05:30:43 srivasta Exp $
.TH ANGBAND 6 "February 16 1998" "Debian" "Debian GNU/Linux manual"
.SH NAME
angband \- is a graphical dungeon adventure game in the vein of rogue
.SH SYNOPSIS
.B angband
.I [options]
.I [\-\- suboptions]
.SH DESCRIPTION
This manual page explains the Debian package
.B "angband".
.B Angband 
is a single-player, 
.I graphical
dungeon adventure game using textual characters
to represent the walls and floors of a dungeon and the inhabitants therein,
in the vein of 
.I rogue, 
.I hack, 
.I nethack, 
and 
.I moria.
.B Angband 
3.2.0 is an official stable release incorporating all the changes
and improvements added since the last official stable release (
.B Angband 
3.0.9b).
.PP
This version of
.B Angband
has been compiled with 
.I ncurses
and the 
.I X Windowing system, SDL and GTK
front-ends, and hence can be played on a virtual console as well as under 
.I X.
In the latter cases, the game can use multiple windows.
.SH OPTIONS
.PD 0
.TP 10
.B \-h 
Print out a usage message.
.TP
.BR \-n
Start a new character
.TP
.BR \-w
Request wizard mode (no high score entry)
.TP
.BR \-g
Request graphics mode
.TP
.BR \-r
Rebalance monsters
.TP
.BR \-s<num>  
Show <num> high scores
.TP
.BR \-u<who>  
Use your <who> savefile
.TP
.BR \-m<sys>  
Use <sys> core code (e.g. gcu for console mode, x11 or sdl for graphics)
.TP
.BR \-d<lib>=<path>  
Define a \'lib\' dir sub-path. Valid values of lib are help info user
bone save data apex xtra edit file
.PD
.SH "GETTING STARTED"
To start with, you can just say angband \-uTest, and that creates a
save file with the file name 
.I ~/.angband/Angband/save/<UID>.Test.
The best place to get help is the program itself; help is reached by
the command
.B ?
and presents a menu of choices.
.PP
Program options can be set  using the = command. To see what the
various options mean, access the List of Options help menu with the ?
command. 
.SH "SEE ALSO"
.BR nethack (6).
.SH AUTHOR
This manual page was written Manoj Srivastava <srivasta@debian.org>,
for the Debian GNU/Linux system.
