/**
 * \file list-mon-message.h
 * \brief List of monster message types
 *
 * id   - the message constant name
 * msg  - MSG_ type for the printed message
 * text - the message text
 */

/* id						MSG_GENERIC,	text */
MON_MSG(NONE,				MSG_GENERIC,	"[is|are] hurt.")
MON_MSG(DIE,				MSG_KILL,		"die[s].")
MON_MSG(DESTROYED,			MSG_KILL,		"[is|are] destroyed.")
MON_MSG(RESIST_A_LOT,		MSG_GENERIC,	"resist[s] a lot.")
MON_MSG(HIT_HARD,			MSG_GENERIC,	"[is|are] hit hard.")
MON_MSG(RESIST,				MSG_GENERIC,	"resist[s].")
MON_MSG(IMMUNE,				MSG_GENERIC,	"[is|are] immune.")
MON_MSG(RESIST_SOMEWHAT,	MSG_GENERIC,	"resist[s] somewhat.")
MON_MSG(UNAFFECTED,			MSG_GENERIC,	"[is|are] unaffected!")
MON_MSG(SPAWN,				MSG_GENERIC,	"spawn[s]!")
MON_MSG(HEALTHIER,			MSG_GENERIC,	"look[s] healthier.")
MON_MSG(FALL_ASLEEP,		MSG_GENERIC,	"fall[s] asleep!")
MON_MSG(WAKES_UP,			MSG_GENERIC,	"wake[s] up.")
MON_MSG(CRINGE_LIGHT,		MSG_GENERIC,	"cringe[s] from the light!")
MON_MSG(SHRIVEL_LIGHT,		MSG_KILL,		"shrivel[s] away in the light!")
MON_MSG(LOSE_SKIN,			MSG_GENERIC,	"lose[s] some skin!")
MON_MSG(DISSOLVE,			MSG_KILL,		"dissolve[s]!")
MON_MSG(CATCH_FIRE,			MSG_GENERIC,	"catch[es] fire!")
MON_MSG(BADLY_FROZEN,		MSG_GENERIC,	"[is|are] badly frozen.")
MON_MSG(SHUDDER,			MSG_GENERIC,	"shudder[s].")
MON_MSG(CHANGE,				MSG_GENERIC,	"change[s]!")
MON_MSG(DISAPPEAR,			MSG_GENERIC,	"disappear[s]!")
MON_MSG(MORE_DAZED,			MSG_GENERIC,	"[is|are] even more stunned.")
MON_MSG(DAZED,				MSG_GENERIC,	"[is|are] stunned.")
MON_MSG(NOT_DAZED,			MSG_GENERIC,	"[is|are] no longer stunned.")
MON_MSG(MORE_CONFUSED,		MSG_GENERIC,	"look[s] more confused.")
MON_MSG(CONFUSED,			MSG_GENERIC,	"look[s] confused.")
MON_MSG(NOT_CONFUSED,		MSG_GENERIC,	"[is|are] no longer confused.")
MON_MSG(MORE_SLOWED,		MSG_GENERIC,	"look[s] more slowed.")
MON_MSG(SLOWED,				MSG_GENERIC,	"look[s] slowed.")
MON_MSG(NOT_SLOWED	,		MSG_GENERIC,	"speed[s] up.")
MON_MSG(MORE_HASTED,		MSG_GENERIC,	"look[s] even faster!")
MON_MSG(HASTED,				MSG_GENERIC,	"start[s] moving faster.")
MON_MSG(NOT_HASTED,			MSG_GENERIC,	"slow[s] down.")
MON_MSG(MORE_AFRAID,		MSG_GENERIC,	"look[s] more terrified!")
MON_MSG(FLEE_IN_TERROR,		MSG_FLEE,		"flee[s] in terror!")
MON_MSG(NOT_AFRAID,			MSG_GENERIC,	"[is|are] no longer afraid.")
MON_MSG(MORIA_DEATH,		MSG_KILL,		"~You hear [a|several] scream[|s] of agony!")
MON_MSG(DISINTEGRATES,		MSG_KILL,		"disintegrate[s]!")
MON_MSG(FREEZE_SHATTER,		MSG_KILL,		"freeze[s] and shatter[s]!")
MON_MSG(MANA_DRAIN	,		MSG_GENERIC,	"lose[s] some mana!")
MON_MSG(BRIEF_PUZZLE,		MSG_GENERIC,	"look[s] briefly puzzled.")
MON_MSG(MAINTAIN_SHAPE,		MSG_GENERIC,	"maintain[s] the same shape.")
MON_MSG(UNHARMED,			MSG_GENERIC,	"[is|are] unharmed.")
/* Dummy messages for monster pain - we use edit file info instead. */
MON_MSG(95,					MSG_GENERIC,	"")
MON_MSG(75,					MSG_GENERIC,	"")
MON_MSG(50,					MSG_GENERIC,	"")
MON_MSG(35,					MSG_GENERIC,	"")
MON_MSG(20,					MSG_GENERIC,	"")
MON_MSG(10,					MSG_GENERIC,	"")
MON_MSG(0,					MSG_GENERIC,	"")
MON_MSG(MAX,				MSG_GENERIC,	"")
