/**
 * \file list-tvals.h
 * \brief List of object base types
 */
/* string		name 			min randarts */
TV(NULL,		"none",			0)
TV(CHEST,		"chest",		0)
TV(SHOT,		"shot",			0)
TV(ARROW,		"arrow",		0)
TV(BOLT,		"bolt",			0)
TV(BOW,			"bow",			4)
TV(DIGGING,		"digger",		0)
TV(HAFTED,		"hafted",		5)
TV(POLEARM,		"polearm",		5)
TV(SWORD,		"sword",		5)
TV(BOOTS,		"boots",		4)
TV(GLOVES,		"gloves",		4)
TV(HELM,		"helm",			3)
TV(CROWN,		"crown",		1)
TV(SHIELD,		"shield",		4)
TV(CLOAK,		"cloak",		4)
TV(SOFT_ARMOR,	"soft armor",	2)
TV(HARD_ARMOR,	"hard armor",	2)
TV(DRAG_ARMOR,	"dragon armor",	1)
TV(LIGHT,		"light",		3)
TV(AMULET,		"amulet",		3)
TV(RING,		"ring",			3)
TV(STAFF,		"staff",		0)
TV(WAND,		"wand",			0)
TV(ROD,			"rod",			0)
TV(SCROLL,		"scroll",		0)
TV(POTION,		"potion",		0)
TV(FLASK,		"flask",		0)
TV(FOOD,		"food",			0)
TV(MUSHROOM,	"mushroom",		0)
TV(MAGIC_BOOK,	"magic book",	0)
TV(PRAYER_BOOK,	"prayer book",	0)
TV(NATURE_BOOK,	"nature book",	0)
TV(DEATH_BOOK,	"death book",	0)
TV(OTHER_BOOK,	"other book",	0)
TV(GOLD,		"gold",			0)
