/**
 * \file list-player-timed.h
 * \brief timed player properties
 *
 * Fields:
 * symbol - the effect name
 * flag_redraw - the things to be redrawn when the effect is set
 * flag_update - the things to be updated when the effect is set
 * oflag_dup - object flag that is redundant with the timed effect
 * oflag_is_syn - if true, oflag_dup is synonymous with the timed effect (except
 * for duration); otherwise, the timed effect has other effects besides those
 * implied by oflag_dup
 * oflag_cure - curing the effect would be (mostly) irrelevant if the player
 * had this object property flag (i.e. a protection of some sort)
 * elem_dup - element index for the temporary resistance granted by the timed
 * effect (ELEM_MAX for no such temporary resistance)
 * brand_name_dup - name of brand that is redundant with the timed effect
 * slay_name_dup - name of slay that is redundant with the timed effect
 */

/* symbol flag_redraw flag_update oflag_dup oflag_is_syn oflag_cure elem_dup brand_name_dup slay_name_dup */
TMD(FAST, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SLOW, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(BLIND, PR_MAP, PU_UPDATE_VIEW | PU_MONSTERS,
	OF_NONE, false, OF_PROT_BLIND, ELEM_MAX, NULL, NULL)
TMD(PARALYZED, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_FREE_ACT, ELEM_MAX, NULL, NULL)
TMD(CONFUSED, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_PROT_CONF, ELEM_MAX, NULL, NULL)
TMD(AFRAID, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_PROT_FEAR, ELEM_MAX, NULL, NULL)
TMD(IMAGE, PR_MAP | PR_MONLIST | PR_ITEMLIST, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(POISONED, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(CUT, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(STUN, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_PROT_STUN, ELEM_MAX, NULL, NULL)
TMD(FOOD, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(PROTEVIL, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(INVULN, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(HERO, PR_STATUS, PU_BONUS,
	OF_PROT_FEAR, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SHERO, PR_STATUS, PU_BONUS,
	OF_PROT_FEAR, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SHIELD, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(BLESSED, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SINVIS, PR_STATUS, PU_BONUS | PU_MONSTERS,
	OF_SEE_INVIS, true, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SINFRA, PR_STATUS, PU_BONUS | PU_MONSTERS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(OPP_ACID, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_ACID, NULL, NULL)
TMD(OPP_ELEC, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_ELEC, NULL, NULL)
TMD(OPP_FIRE, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_FIRE, NULL, NULL)
TMD(OPP_COLD, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_COLD, NULL, NULL)
TMD(OPP_POIS, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_POIS, NULL, NULL)
TMD(OPP_CONF, PR_STATUS, PU_BONUS,
	OF_PROT_CONF, true, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(AMNESIA, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(TELEPATHY, PR_STATUS, PU_BONUS,
	OF_TELEPATHY, true, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(STONESKIN, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(TERROR, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SPRINT, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(BOLD, PR_STATUS, PU_BONUS,
	OF_PROT_FEAR, true, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(SCRAMBLE, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(TRAPSAFE, PR_STATUS, PU_BONUS,
	OF_TRAP_IMMUNE, true, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(FASTCAST, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(ATT_ACID, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, "ACID_3", NULL)
TMD(ATT_ELEC, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, "ELEC_3", NULL)
TMD(ATT_FIRE, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, "FIRE_3", NULL)
TMD(ATT_COLD, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, "COLD_3", NULL)
TMD(ATT_POIS, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, "POIS_3", NULL)
TMD(ATT_CONF, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(ATT_EVIL, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, "EVIL_2")
TMD(ATT_DEMON, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, "DEMON_5")
TMD(ATT_VAMP, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(HEAL, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(COMMAND, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(ATT_RUN, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(COVERTRACKS, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(POWERSHOT, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(TAUNT, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(BLOODLUST, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(BLACKBREATH, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(STEALTH, PR_STATUS, PU_BONUS,
	OF_NONE, false, OF_NONE, ELEM_MAX, NULL, NULL)
TMD(FREE_ACT, PR_STATUS, PU_BONUS,
	OF_FREE_ACT, true, OF_NONE, ELEM_MAX, NULL, NULL)
