#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

include $(DEVKITARM)/ds_rules

# Use Makefile.src to not include any of the dependencies or rules
include Makefile.src

# Set default goal to be "all", because Makefile.src messes that up
.DEFAULT_GOAL		:=	all

export TARGET		:=	$(PROGNAME)
export TOPDIR		:=	$(CURDIR)

# Export object lists for access in arm9 Makefile
# (directly including Makefile.src there messes up our default targets)
export ANGFILES		:=	$(ANGFILES)
export ZFILES		:=	$(ZFILES)

.PHONY: checkarm7 checkarm9

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
all: checkarm7 checkarm9 $(TARGET).nds

#---------------------------------------------------------------------------------
$(TARGET).nds	:	$(TARGET).arm7.elf $(TARGET).arm9.elf
	ndstool	-c $(TARGET).nds -7 $(TARGET).arm7.elf -9 $(TARGET).arm9.elf -h 0x200

#---------------------------------------------------------------------------------
checkarm7 $(TARGET).arm7.elf:
	$(MAKE) -f Makefile.nds.arm7
	
#---------------------------------------------------------------------------------
checkarm9 $(TARGET).arm9.elf:
	$(MAKE) -f Makefile.nds.arm9

#---------------------------------------------------------------------------------
clean:
	$(MAKE) -f Makefile.nds.arm9 clean
	$(MAKE) -f Makefile.nds.arm7 clean
	rm -f $(TARGET).nds $(TARGET).arm7 $(TARGET).arm9
