MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

LIBDATA = 5x8x.fon 6x10x.fon 8x8x.fon 8x8xb.fon 8x12x.fon 8x12xb.fon 8x16x.fon \
       10x14x.fon 10x14xb.fon 12x18x.fon 16x16x.fon 16x24x.fon
PACKAGE = xtra/font
